server:
    port: 9090
spring:
    data:
        mongodb:
            authentication-database: admin
            database: KryServiceStatus
            host: localhost
            password: password
            port: 27017
            username: admin
    jpa:
        properties:
            hibernate:
                ogm:
                    datastore:
                        create_database: true
update:
    rate: 5000
