server:
  port: 9090
spring:
  data:
    mongodb:
      database: KryServiceStatus
      host: localhost
      port: 27017
      username: admin
      password: password
      authentication-database: admin
  jpa:
    properties:
      hibernate:
        ogm:
          datastore:
            create_database: true
